-- Create the videos table
create table public.videos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  video_url text not null,
  title text,
  channel_name text,
  transcript text,
  summary_structured text,
  spiritual_essence text,
  quote text,
  image_prompt text,
  image_url text
);

-- Enable Row Level Security (RLS)
alter table public.videos enable row level security;

-- Create policies to allow access via the Anon Key
-- Allow anyone to insert new videos
create policy "Enable insert for all users" 
on public.videos 
for insert 
with check (true);

-- Allow anyone to read videos
create policy "Enable read for all users" 
on public.videos 
for select 
using (true);
